# API Gateway 配置文件

# 服務器配置
server:
  port: 8088
  mode: development # development, staging, production
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60
  max_body_size: 33554432 # 32MB

# 數據庫配置 (可選)
database:
  driver: postgres
  host: localhost
  port: 5432
  database: gateway_db
  username: postgres
  password: password
  ssl_mode: disable

# Redis配置
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

# JWT配置
jwt:
  secret: "your-super-secret-jwt-key-change-in-production"
  expire_duration: 1h
  refresh_duration: 24h

# 微服務路由配置
routes:
  config_file: "configs/services.yaml"
  auto_reload: true
  reload_interval: 30s

# 限流配置
rate_limit:
  enabled: true
  global_limit: 1000
  ip_limit:
    requests: 100
    window: 1m
  user_limit:
    requests: 200
    window: 1m
  api_limit:
    "/api/v1/auth/login":
      requests: 10
      window: 1m
    "/api/v1/users":
      requests: 50
      window: 1m
    "/api/v1/expenses":
      requests: 30
      window: 1m

# 負載均衡配置
load_balance:
  strategy: round_robin # round_robin, weighted_round_robin, least_connections
  health_check:
    enabled: true
    interval: 30s
    timeout: 5s
    path: /health
  services:
    user-service:
      name: user-service
      instances:
        - "localhost:8001"
        - "localhost:8002"
      weight: 1
    order-service:
      name: order-service
      instances:
        - "localhost:8003"
        - "localhost:8004"
      weight: 1
    payment-service:
      name: payment-service
      instances:
        - "localhost:8005"
      weight: 1

# 監控配置
monitor:
  enabled: true
  metrics_path: "/metrics"
  prometheus_enabled: true

# 安全配置
security:
  cors:
    allow_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
      - "*"
    allow_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allow_headers:
      - "*"
    allow_credentials: true
  csp:
    enabled: false
    policy: "default-src 'self'"
  xss:
    enabled: true
  sql_injection:
    enabled: true

# 日誌配置
logging:
  level: info # debug, info, warn, error
  format: json # json, console
  output: stdout # stdout, file
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days

app:
  name: "AI 智能報銷系統 API Gateway"
  version: "1.0.0"
  port: 8088
  mode: "release"
  use_dynamic_routing: true
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

log:
  level: "info"
  format: "json"
  output: "stdout"

cors:
  enabled: true
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "PATCH"
  allowed_headers:
    - "*"
  max_age: 86400

discovery:
  type: "static"
  interval: 30s
  timeout: 5s
  services:
    user-service:
      hosts:
        - "localhost"
      port: 8081
      health_check: "/health"
      headers:
        X-Service-Name: "user-service"
      max_body_size: 10485760  # 10MB
    
    expense-service:
      hosts:
        - "localhost"
      port: 8082
      health_check: "/health"
      headers:
        X-Service-Name: "expense-service"
      max_body_size: 52428800  # 50MB
    
    approval-service:
      hosts:
        - "localhost"
      port: 8083
      health_check: "/health"
      headers:
        X-Service-Name: "approval-service"
      max_body_size: 10485760  # 10MB
    
    finance-service:
      hosts:
        - "localhost"
      port: 8084
      health_check: "/health"
      headers:
        X-Service-Name: "finance-service"
      max_body_size: 10485760  # 10MB
    
    file-service:
      hosts:
        - "localhost"
      port: 8085
      health_check: "/health"
      headers:
        X-Service-Name: "file-service"
      max_body_size: 104857600  # 100MB
    
    ai-service:
      hosts:
        - "localhost"
      port: 8086
      health_check: "/health"
      headers:
        X-Service-Name: "ai-service"
      max_body_size: 52428800  # 50MB
    
    notification-service:
      hosts:
        - "localhost"
      port: 8087
      health_check: "/health"
      headers:
        X-Service-Name: "notification-service"
      max_body_size: 10485760  # 10MB
    
    gateway-service:
      hosts:
        - "localhost"
      port: 8088
      health_check: "/health"
      headers:
        X-Service-Name: "gateway-service"
      max_body_size: 1048576  # 1MB
